project:
  type: website

website:
  title: "Transitional Justice Research Collaborative"
  navbar:
    # logo: images/tjrc.jpg
    left:
      - href: index.qmd
        text: Home
      - href: browse.qmd
        text: Browse
      - href: download.qmd
        text: Download
      - href: findings.qmd
        text: Findings
      - href: faq.qmd
        text: FAQ
      - href: feedback.qmd
        text: Feedback
      - href: about.qmd
        text: About
      - href: people.qmd
        text: People
      - href: links.qmd
        text: Links

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    # title-block-banner: images/tjrc.jpg
    # title-block-style: default
    # include-in-header: html/header.html

editor: visual

