project:
  type: website

format:
  html:
    theme: yeti
    toc: true
    df-print: kable

website:
  title: "Transitional Justice Research Collaborative"
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: browse.qmd
        text: "Browse Data"
      - href: download.qmd
        text: "Download"
      - href: findings.qmd
        text: "Findings"
      - href: faq.qmd
        text: "FAQ"
      - href: feedback.qmd
        text: "Feedback"
      - href: about.qmd
        text: "About"
      - href: people.qmd
        text: "People"
      - href: links.qmd
        text: "Links"
  body-footer: _footer.qmd
  page-footer:
    right: |
      This site was recreated by [Oskar Timo Thoms](https://oskarthoms.net) on behalf of TJET/TJRC and built with [Quarto](https://quarto.org/) and the [reactable](https://glin.github.io/reactable/) package.
    border: true
    background: light
    foreground: black
