project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "Transitional Justice Research Collaborative"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: download.qmd
        text: "Download"
      - href: findings.qmd
        text: "Findings"
      - href: faq.qmd
        text: "FAQ"
      - href: about.qmd
        text: "About"
      - href: people.qmd
        text: "People"
      - href: links.qmd
        text: "Links"
