---
title: "About"
---

The **Transitional Justice Research Collaborative** began with support from the National Science Foundation (NSF) and the Arts and Humanities Research Council (AHRC) in June 2010, and it ceased updating in 2018. Members of the project, Geoff Dancy and Kathryn Sikkink, will soon go live with a new database called the Transitional Justice Evaluation Tools (TJET). TJET will present data updates on transitional justice mechanisms through 2020.

The main purpose of the Transitional Justice Research Collaborative was to produce data and use the data to understand the impact of justice mechanisms on human rights and democracy around the world.

The two principal investigators for this project were Professor Leigh Payne, at the Sociology Department and at the Latin American Centre at the University of Oxford, and Professor Kathryn Sikkink, professor emeritus at the Department of Political Science at the University of Minnesota, and the Ryan Family Professor at the Kennedy School of Government at Harvard University. From 2010-2013, the Transitional Justice Research Collaborative collected and analyzed detailed data about three main transitional justice mechanisms: human rights prosecutions, truth commissions, and amnesty laws. Beginning in June 2010, the project operated under the joint direction of Geoff Dancy and Francesca Lessa, with Bridget Marchesi joining them in 2012. In addition to the directors, many graduate students and now assistant professors have performed invaluable services as coders, individual project directors, and consultants. Together, the team has generated coding instruments, web-based entry techniques, research methods, and data analysis for the three mechanisms under examination. For a full listing of our dedicated coders, project directors, and consultants, see [People](people.html).

The Transitional Justice Research Collaborative built off the earlier work of Payne and Sikkink's two previous research teams. The first was the Transitional Justice Data Base project in the Department of Political Science at the University of Wisconsin-Madison, and the second was the Transitional Human Rights Trials project in the Department of Political Science at the University of Minnesota. The research at the University of Wisconsin culminated in the publication of a book co-authored by Tricia Olsen, Leigh Payne and Andrew Reiter: **Transitional Justice in Balance: Comparing Processes, Weighing Efficacy** (Washington, DC: United States Institute of Peace Press, 2010) and numerous journal articles. The research at the University of Minnesota produced journal articles authored by Hun Joon Kim, Carrie Booth-Walling, and Kathryn Sikkink, as well as Kathryn Sikkink's 2011 book **The Justice Cascade: How Human Rights Prosecutions are Changing World Politics** (New York: W.W. Norton). For a list of publications using the Transitional Justice Research Collaborative data, see [Findings](findings.html).
