---
title: "Frequently Asked Questions"
---

### Why did you select these three mechanisms---trials, truth commissions, and amnesties

State governments acting to right the wrongs of the past in the wake of democratic transitions have a number of justice policy options available. We have collected extensive data on these three mechanisms because they are the most grounded in the theoretical literature on transitional justice, and they remain the most common in practice. Even further, while the 1990s and 2000s saw an overwhelming increase in the use of these mechanisms, little effort has been made to systematically gauge their impacts. Our data is meant to help address this deficit in cross-national analysis.

### How did you select which countries to include in the browse?

Not all of the countries of the world are included in our browse. We do not even include all of the countries for which we have collected data. The expressed purpose of the data presented on this website is to enable analysis of the impact of international and domestic transitional justice efforts among countries in the wake of democratic transition. For us, this means excluding events that take place in non-democratic and non-transitional contexts. To determine whether a country can be classified as "transitional," we carefully reviewed regime type data collected by the Polity IV Project at the University of Maryland. See the file "Democratic Transitions" on the [Download](download.html) page of our site.

All of those countries that experienced at least one democratic transition, or emerged as a new democratic state were included in our sample. We begin our sample with the year 1970 since transitional justice is often seen as an issue that emerged with the Third Wave of Democratization and because human rights-related data prior to this year are unreliable.

These countries remained in our sample as long as they did not revert back to authoritarian rule. In the event that they did revert, the years under autocracy were excluded, though the country years under democracy remain in our dataset. In the event that a country experienced multiple transitions---meaning that it transitioned to democracy, reverted to autocracy, and again transitioned to democracy---only those country years falling under democratic rule were included in the dataset.

Therefore, the countries you see in the browse, and the corresponding data, take place in post-transitional, and at least minimally democratic, contexts. For more information, please refer to our coding manual on the [Download](download.html) page.

### How do you know that certain mechanisms are 'transitional' justice efforts, rather than 'normal' justice efforts?

This is a difficult question to answer, and it is one that we have extensively considered. The transitional status of justice mechanisms can only be defined in terms of time and space or political context. Thus, to mark 'transitional' mechanisms, we create scope conditions and definitional criteria that delimit which actions are occurring during institutional or political flux.

For a human rights trial to be transitional it must occur after the democratic transition and it must seek remedy for crimes that were committed prior to that transition. In addition, the accused must be state agents, who have engaged in violations of physical integrity.

For a truth commission to be transitional it must similarly have occurred in the wake of transition and it must endeavor to provide truth for state crimes that took place under autocratic rule.

Finally, for an amnesty to be considered transitional, it must seek indemnity for state actions under autocratic rule. A critical exception exists for our coding of amnesties; an amnesty can be considered transitional even if it was passed prior to democratic transition.

### What is a human rights trial or prosecution?

We define a human rights criminal prosecution as "the use of domestic, foreign, or international courts of law to bring criminal procedures--including preliminary trial processes, trial hearings, or verdict and sentencing--against state agent perpetrators of human rights violations." Human rights prosecutions encompass a variety of actions made by a number of actors. They have also been called human right trials, and they can include actions taken by the International Criminal Court (ICC) or ad hoc tribunals (as in the Slobodan Milosevic trial); foreign courts bringing charges against nationals of another country (as in the Augusto Pinochet case); or domestic courts bringing charges against their own nationals (as in Guatemala's Rios Montt trial).

### Why do you use quantitative instead of qualitative data?

We resist this distinction. Our project is often considered to be 'quantitative' because we have used numerical coding to analyze developments in cross-national time-series data sets. However, our work is not exclusively, or even primarily, quantitative. Nearly all of our coding work has involved scouring information in governmental, non-governmental, and journalistic accounts. We then generate a narrative account that is then categorized and input into a number of electronic data entry fields.

### What are your sources?

We primarily rely on US State Department Human Rights Reports as a starting point for our research on trials. We chose to do so because these reports provide an uninterrupted record of events in each country since the late 1970s and because the exclusive focus of these reports is on human rights practices.

In order to extend our information back to 1970, we used Keesing's Record of World Events. This source, while extremely useful, demonstrates a tendency toward national security objectives. For example, many of the trials listed in Keesing's refer to attempts to hold coup-leaders accountable for crimes against the state. Such actions do not fall within the purview of our analysis. However, we have still used Keesing's to supplement the record kept by the US State Department.

After coders read every US State Department report in search for at least one recorded instance of human rights trial activity, they made a list of all the country-years of the world that arguably contained transitional human rights trials. Next, all country-years coded as having a trial activity by Olsen et al. in Transitional Justice in Balance (2010) were added to the list. Coders then researched each instance further using Lexis Nexis Academic and other sources specific to each country.

For truth commissions, we started with three previous data compilations: Priscilla Hayner's data in Unspeakable Truths, 2nd Edition, Dancy et al.'s (2010) Truth Commission Database, and truth commissions listed on the US Institute of Peace Website. Our coders then performed additional research on each case to arrive at the specific information needed to fill the record.

For amnesties, the team began with data collected by Louise Mallinder (2008), and supplemented the list with information from Olsen et al. in Transitional Justice in Balance (2010). They then performed additional research to arrive at more specific details.

### Is this a complete record of transitional justice events?

No, and we do not claim that it is. While we are confident that we have covered almost all truth commissions and amnesties, we cannot know whether we have captured all human rights trials that have taken place everywhere in the world. We collected 7,523 accused and 4,686 trial listings in 153 country jurisdictions, though we consider only 1,149 accused in 508 trials in 65 countries to be transitional in nature. Yet, despite these large numbers, we cannot know how many cases we have overlooked, or how much retrievable information is missing from the records. This is not necessarily a problem specific to our data, but a problem with all event history data. However, we have not let our desire to be comprehensive prevent us from being pragmatic, and we will release the data with the understanding that it is a never-ending work in progress.

{{< include _footer.qmd >}}

